### ISSUE TITLE
I get an exception if I enter a non-number into the "choose a race" field

### ISSUE THREAD

**Issue by tbird20d** [tbird20d/python-text-games#10]
I get an exception if I put 'elf' in as my race selection.
Please see the following steps to reproduce this problem.

```
Choose a race
1- Human		2- Elf		3- Orc
My race is: elf
Traceback (most recent call last):
  File "./knight-training", line 258, in <module>
    main()
  File "./knight-training", line 227, in main
    create_hero()
  File "./knight-training", line 105, in create_heroe_choice = int(input("My race is: "))
ValueError: invalid literal for int() with base 10: 'elf'
```

**Comment by tbird20d** [comment]
Fixed by commit 592fd13f18687142758c10d65e47b476df56bf17

**Comment by tbird20d** [comment]
This bug was resolved
